import numpy as np
import pytest

from src.classification.rl_classifier import RLAttackClassifier
from src.utils.data_loader import generate_detection_dataset
from tests.fixtures.mock_data import make_synthetic_participants as _make_synthetic_participants


class TestRLAttackClassifierUnit:
    def test_classify_output_shape(self):
        classifier = RLAttackClassifier(n_attacks=5)
        idx, confidence = classifier.classify([0.1, 0.2, 0.3, 0.4])
        assert 0 <= idx < 5
        assert 0.0 <= confidence <= 1.0

    def test_train_reduces_loss_on_learnable_signal(self):
        rng = np.random.default_rng(1)
        X = rng.standard_normal((300, 4)).astype(np.float32)
        y = (X[:, 0] > 0).astype(np.int64)
        classifier = RLAttackClassifier(n_attacks=2)
        losses = classifier.train(X, y, epochs=15, batch_size=32, verbose=False)
        assert losses[-1] < losses[0]

    def test_save_and_load_roundtrip(self, tmp_path):
        classifier = RLAttackClassifier(n_attacks=3)
        classifier.classify([0.0, 0.0, 0.0, 0.0])  # force build
        path = str(tmp_path / "clf.weights.h5")
        classifier.save(path)

        loaded = RLAttackClassifier(n_attacks=3)
        loaded.load(path)

        idx1, conf1 = classifier.classify([0.2, 0.5, -0.1, 0.9])
        idx2, conf2 = loaded.classify([0.2, 0.5, -0.1, 0.9])
        assert idx1 == idx2
        assert conf1 == pytest.approx(conf2, rel=1e-5)


class TestRealDetectionSignalClassification:
    """Integration test: generates a real dataset via FL rounds with injected
    attacks (src.utils.data_loader) and verifies the classifier learns to
    discriminate attack types from the detection scores."""

    # sign_flipping and label_flipping produce well-separated detection-score
    # signatures; gaussian_noise/byzantine/poisoning overlap more with each
    # other in this small synthetic configuration.
    ATTACK_TYPES = ["sign_flipping", "label_flipping"]

    @classmethod
    @pytest.fixture(scope="class")
    def dataset(cls):
        participants = _make_synthetic_participants()
        X, y_binary, y_attack_type = generate_detection_dataset(
            participants,
            n_rounds=10,
            attack_types=cls.ATTACK_TYPES,
            byzantine_fraction=0.5,
            aggregation="fedavg",
            n_classes=2,
            seed=42,
        )
        labels = ["none"] + cls.ATTACK_TYPES
        label_to_idx = {label: i for i, label in enumerate(labels)}
        y_idx = np.array([label_to_idx[t] for t in y_attack_type])
        return X, y_binary, y_idx, labels

    def test_dataset_has_both_classes(self, dataset):
        X, y_binary, y_idx, labels = dataset
        assert X.shape[1] == 4
        assert set(np.unique(y_binary)) == {0, 1}
        assert len(np.unique(y_idx)) == len(labels)

    def test_attacked_updates_score_higher_on_average(self, dataset):
        """Verifies the data-generation infrastructure produces real signal:
        attacked updates should, on average, score higher across the 4
        detection modalities than honest updates."""
        X, y_binary, _y_idx, _labels = dataset
        honest_mean = X[y_binary == 0].mean()
        attacked_mean = X[y_binary == 1].mean()
        assert attacked_mean > honest_mean

    def test_classifier_trains_on_real_generated_data(self, dataset):
        """Proves RLAttackClassifier.train() works end-to-end on the real
        dataset generated by generate_detection_dataset, and that the loss
        actually decreases."""
        X, _y_binary, y_idx, labels = dataset
        classifier = RLAttackClassifier(n_attacks=len(labels))
        losses = classifier.train(X, y_idx, epochs=30, batch_size=16, verbose=False)
        assert losses[-1] < losses[0]
